version: "3.9"
services:
  ldap:
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'
    networks:
      - internal
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PORT_NUMBER=7000
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '7000:7000'
    networks:
      - internal
  app:
    image: app
    build: ./
    command:
      - "/app/server"
    ports:
      - '80:80'
      - '443:443'
    networks:
      - internal
    depends_on:
      - db
      - redis
      - ldap
    environment:
      - LDAP=ldap://ldap:1389
      - REDIS=redis://redis:7000
      - DB=postgresql://user1:changeme@db:5432/ofac
      - DATABASE_URL=postgresql://user1:changeme@db:5432/ofac
      - RUST_LOG=debug
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: ofac
    networks:
      - internal
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    ports:
      - 5432:5432

networks:
  internal:


volumes:
  openldap_data:
    driver: local
  postgres_data:
    driver: local
