version: "3.9"
services:
  ldap:
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    volumes:
      - 'openldap_data:/bitnami/openldap'
    networks:
      - internal
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PORT_NUMBER=7000
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '7000:7000'
    networks:
      - internal
  back:
    image: back
    build: ./back
    command:
      - "/app/server"
    ports:
      - '8000:8000'
    networks:
      - internal
    links:
      - "redis"
      - "ldap"
    environment:
      - LDAP=ldap://ldap:1389
      - REDIS=redis://redis:7000

networks:
  internal:


volumes:
  openldap_data:
    driver: local
  #front:
  #  image: front
  #  build: ./front
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.front.rule=PathPrefix(`/`)"
  #    - "traefik.http.routers.front.entrypoints=web"
  #    - "traefik.http.services.front.loadbalancer.server.port=80"
  #  ports:
  #    - 80
  #  networks:
  #    - internal

  #traefik:
  #  image: "traefik:v2.5"
  #  container_name: "traefik"
  #  command:
  #    #- "--log.level=DEBUG"
  #    - "--api.insecure=true"
  #    - "--providers.docker=true"
  #    - "--providers.docker.exposedbydefault=false"
  #    - "--entrypoints.web.address=:80"
  #  ports:
  #    - "80:80"
  #    - "8080:8080"
  #  networks:
  #    - internal
  #  volumes:
  #    - "/var/run/docker.sock:/var/run/docker.sock:ro"

